Django1-5 Review/review_project/review_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from staff_data import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'staffdata/',include ('staff_data.urls')),
]

Django1-5 Review/review_project/staff_data/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from staff_data import views
from django.contrib.auth.views import login

app_name = "staff_data"
urlpatterns = [
    url(r'staffpage',views.staffpage, name = "staffpage"),
    url(r'staffform',views.staffform, name = "staffform"),
    url(r'$', views.index, name = "index"),
    url(r'^staff_login/$', views.staff_login, name = "staff_login_name")
]

Django1-5 Review/review_project/staff_data/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class StaffProfileInfo(models.Model):
    staff = models.OneToOneField(User)
    protfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)
    def __str__(self):
        return self.staff.username

Django1-5 Review/review_project/staff_data/forms.py
from django import forms
from django.contrib.auth.models import User
from staff_data.models import StaffProfileInfo

class StaffForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ("username","email","password")


class StaffProfileInfoForm(forms.ModelForm):
    class Meta():
        model = StaffProfileInfo
        fields = ('protfolio_site','profile_pic')

Django1-5 Review/review_project/staff_data/views.py
from django.shortcuts import render
from staff_data.models import StaffProfileInfo
from staff_data.forms import StaffForm, StaffProfileInfoForm
from django import forms
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(request):
    print("views.index is running")

    return render(request,"staff_data/index.html")



def staffpage(request):

    staff_dict = StaffProfileInfo.objects.all()
    return render(request,"staff_data/staff_page.html", context = {"staff_data":staff_dict})



def staffform(request):
    registered = False
    if request.method =="POST":
        form_dict_1 = StaffForm(data = request.POST)
        form_dict_2 = StaffProfileInfoForm(data = request.POST)

        if form_dict_1.is_valid() and form_dict_2.is_valid():
            staff = form_dict_1.save()
            staff.set_password(staff.password)
            staff.save()
            profile = form_dict_2.save(commit = False)
            profile.staff = staff
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(form_dict_1.errors, form_dict_2.errors)
    else:
        form_dict_1 = StaffForm()
        form_dict_2 = StaffProfileInfoForm()
    return render(request,"staff_data/staff_form.html",{'form':form_dict_1 , 'profile_form':form_dict_2,'registered':registered})


def staff_login(request):
    print("views.staff_login is running")

    if request.method == "POST":
        staffname = request.POST.get('username')
        password = request.POST.get('password')
        staff = authenticate(username = staffname, password = password)
        if staff:
            if staff.is_active:
                print("staff is active")
                login(request,staff)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Inactive")
        else:
            print("Failed Login Attempt")
            print("Username:{} and password:{}".format(staffname, password))
            return HttpResponse("Invalid username or password")
    else:
        print("rendering login.html")
        return render(request, "staff_data/login.html",{})

@login_required
def staff_logout(request):
    print("views.staff_logout is running")
    logout(request)
    return HttpResponseRedirect(reverse('index'))

Django1-5 Review/review_project/templates/staff_data/index.html
<html>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


<nav class = "navbar navbar-expand-lg navbar-light bg-light">
    <div class = "container">
        <ul class="nav navbar-nav">
            <li><a class = "navbar-brand" href = "{% url "staff_data:staffpage" %}">Staff Page</a>
            <li><a class = "navbar-brand" href = "{% url "staff_data:staffform" %}">Staff Form</a>
            <li><a class = "navbar-brand" href = "{% url "staff_data:index" %}">Index</a>
            <li><a class = "navbar-brand" href = "{% url "admin:index" %}">Site Administration</a>
            {% if staff.is_authenticated %}
                <li><a class = 'navbar-link' href = "{% url 'logout' %}"}>Logout</a>
            {% else %}
                <li><a class= 'navbar-link' href = "{% url "staff_data:staff_login_name" %}"> Login</a>

            {% endif %}
        </ul>
    </div>
</nav>
{% block body-block %}
<title>Index Page</title>

<h1>Index Page</h1>

{% endblock %}

</html>

Django1-5 Review/review_project/templates/staff_data/login.html
{% comment %} {% extends "staff_data/index.html" %} {% endcomment %}



{% comment %} {% block body-block %} {% endcomment %}
    <title>Login Page</title>
    <form action ="{% url: "staff_data:staff:login" %}" method = "POST">
        {% csrf_token %}
        <label for="username">Username:</lable>
        <input type = "text" name = "username" placeholder = "Enter Username">
        <label for="password">Password:</lable>
        <input type = "text" name = "password">
        <input type = "submit" name ="" value = "Login">
    </form>

{% comment %} {% endblock %}} {% endcomment %}

Django1-5 Review/review_project/templates/staff_data/staff_form.html
{% extends "staff_data/index.html" %}
{% block body-block %}
<title>Staff Form</title>


{% if registered == False %}
<h1>Staff Form</h1>
<div class = "container">
    <form enctype = "multipart/form-data" method ="POST">
        {% csrf_token %}
        {{form.as_p}}
        {{profile_form.as_p}}
        <input type = "submit" class = "btn btn-primary" value = "Submit">
    </form>
</div>
{% else %}
<h1>Thank You for Registering</h1>

{% endif %}
{% endblock %}}

Django1-5 Review/review_project/templates/staff_data/staff_page.html
{% extends "staff_data/index.html" %}




{% block body-block %}
<title>Staff Page</title>
<h1>Staff Page</h1>
{% load staticfiles %}

<img src="{% static 'staff_data/logo.jpg' %}"> </img>



<table>
<tr>
    <th>username</th>
    <th>email</th>
</tr>
        {% if staff_data %}
            {% for entry in staff_data%}
                <tr>
                    <td>  {{ entry.id }} </td>
                    <td> {{ entry.staff_id }} </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td> EMPTY </td>
                <td> EMPTY </td>
            </tr>
        {% endif %}

</table>
{% endblock %}